### ISSUE TITLE
错误的方法（？

### ISSUE THREAD

**Issue by tianyisama** [LiteyukiStudio/nonebot-plugin-acgnshow#2]
阿卡林酱，据我所知Pydantic模型没有内置的model_validate方法（）

所以acgnapis.py的第23行是不是该改成return CityResp.parse_obj(regions_data)喵

**Comment by snowykami** [comment]
项目所用v2有的哦，https://docs.pydantic.dev/latest/concepts/models/#validating-data
v1确实没有，不过项目不是用的这个版本

**Comment by tianyisama** [comment]
> 项目所用v2有的哦，https://docs.pydantic.dev/latest/concepts/models/#validating-data
> v1确实没有，不过项目不是用的这个版本

果咩纳塞，火星了（nb还用的v1的pydantic
